<?php

namespace Laswagger\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Laswagger\Swagger\SwaggerGenerator;

/**
 * Swagger controller to access api docs is generated by swagger.
 */
class SwaggerController extends Controller
{

    /**
     * @var SwaggerGenerator
     */
    protected $swaggerGenerator;

    /**
     * SwaggerController constructor.
     *
     * @param SwaggerGenerator $swaggerGenerator
     */
    public function __construct(SwaggerGenerator $swaggerGenerator)
    {
        $this->swaggerGenerator = $swaggerGenerator;
    }

    /**
     * Swagger generate api docs.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        if ($request->getHost()) {
            $this->swaggerGenerator->getOption()
                                   ->setHost($request->getHost());
        }

        $response = new Response($this->swaggerGenerator->generateDocs());

        if (config('laswagger.routes.cors')) {
            $response
                ->header('Access-Control-Allow-Methods', 'GET')
                ->header('Access-Control-Allow-Headers', 'Content-Type')
                ->header('Access-Control-Allow-Origin', '*');
        }

        return $response;
    }
}
